---
title: "class2"
author: "廖昱嘉"
date: "2018年7月11日"
output: html_document
---
## 套件安裝
```{r eval=FALSE}
if(!require(xml2))install.packages("xml2",repos = "http://cran.us.r-project.org")
if(!require(tmcn))install.packages("tmcn",repos = "http://cran.us.r-project.org")
if(!require(NLP))install.packages("NLP",repos = "http://cran.us.r-project.org")
if(!require(tm))install.packages("tm",repos = "http://cran.us.r-project.org")
if(!require(jiebaR))install.packages("jiebaR",repos = "http://cran.us.r-project.org")
if(!require(jiebaRD))install.packages("jiebaRD",repos = "http://cran.us.r-project.org")
if(!require(RColorBrewer))install.packages("RColorBrewer",repos = "http://cran.us.r-project.org")
if(!require(wordcloud))install.packages("wordcloud",repos = "http://cran.us.r-project.org")
if(!require(rvest))install.packages("rvest",repos = "http://cran.us.r-project.org")

library(tmcn)
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(wordcloud)
library(rvest)
library(xml2)
```   
## pttTestFunction
```{r,eval=FALSE}
pttTestFunction <- function(URL, filename)
{
  #URL   = "https://www.ptt.cc/bbs/C_Chat/index.html"
  html  = read_html(URL)
  title = html_nodes(html, "a")
  href  = html_attr(title, "href")
  data = data.frame(title = toUTF8(html_text(title)),
                       href = href)
  data = data[-c(16387:16388),]
  getContent <- function(x) {
    url  = paste0("https://www.ptt.cc", x)
    tag  = html_node(read_html(url), 'div#main-content.bbs-screen.bbs-content')
    text = toUTF8(html_text(tag))
  }
  #getContent(data$href[1])
  allText = sapply(data$href, getContent)
  allText
  #out <- file(filename, "w", encoding="BIG-5") 
  write.table(allText, filename) 
  #close(out) 
}
```
## 網路爬蟲   
```{r,eval=FALSE}
source('pttTestFunction.R')
id = c(16387:16388)
URL = paste0("https://www.ptt.cc/bbs/C_Chat/index", id, ".html")
filename = paste0(id, ".txt")
mapply(pttTestFunction, 
       URL = URL, filename = filename)
```   
## 文本清理   
```{r}
library(tm)
rm(list=ls(all.names = TRUE))
filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))
#移除可能有問題的符號
toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
}
)
docs <- tm_map(docs, toSpace, "※")
docs <- tm_map(docs, toSpace, "◆")
docs <- tm_map(docs, toSpace, "‧")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "我")
docs <- tm_map(docs, toSpace, "是")
docs <- tm_map(docs, toSpace, "看板")
docs <- tm_map(docs, toSpace, "作者")
docs <- tm_map(docs, toSpace, "發信站")
docs <- tm_map(docs, toSpace, "批踢踢實業坊")
docs <- tm_map(docs, toSpace, "[a-zA-Z]")
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
docs <- tm_map(docs, toSpace, "推")
docs <- tm_map(docs, toSpace, "了")
docs <- tm_map(docs, toSpace, "就")
docs <- tm_map(docs, toSpace, "不")
docs <- tm_map(docs, toSpace, "也")
docs <- tm_map(docs, toSpace, "有")
docs <- tm_map(docs, toSpace, "來自")
docs <- tm_map(docs, toSpace, "作者")
docs <- tm_map(docs, toSpace, "閒聊")
docs <- tm_map(docs, toSpace, "時間")
docs <- tm_map(docs, toSpace, "標題")
docs <- tm_map(docs, toSpace, "發信站")
docs <- tm_map(docs, toSpace, "文章網址")
docs <- tm_map(docs, toSpace, "在")
docs <- tm_map(docs, toSpace, "都")
docs <- tm_map(docs, toSpace, "會")
docs <- tm_map(docs, toSpace, "吧")
docs <- tm_map(docs, toSpace, "還")
docs <- tm_map(docs, toSpace, "被")
docs <- tm_map(docs, toSpace, "這")
docs <- tm_map(docs, toSpace, "你")
docs <- tm_map(docs, toSpace, "噓")
docs <- tm_map(docs, toSpace, "說")
docs <- tm_map(docs, toSpace, "要")
docs <- tm_map(docs, toSpace, "看")
docs <- tm_map(docs, toSpace, "人")
docs <- tm_map(docs, toSpace, "嗎")
docs <- tm_map(docs, toSpace, "只")
docs <- tm_map(docs, toSpace, "可以")
docs <- tm_map(docs, toSpace, "真")
docs <- tm_map(docs, toSpace, "到")
docs <- tm_map(docs, toSpace, "啊")
docs <- tm_map(docs, toSpace, "阿")
docs <- tm_map(docs, toSpace, "個")
docs <- tm_map(docs, toSpace, "但")
docs <- tm_map(docs, toSpace, "跟")
docs <- tm_map(docs, toSpace, "很")
docs <- tm_map(docs, toSpace, "什麼")
docs <- tm_map(docs, toSpace, "沒")
docs <- tm_map(docs, toSpace, "那")
docs <- tm_map(docs, toSpace, "好")
docs <- tm_map(docs, toSpace, "啦")
docs <- tm_map(docs, toSpace, "和")
docs <- tm_map(docs, toSpace, "又")
docs <- tm_map(docs, toSpace, "用")
docs <- tm_map(docs, toSpace, "因為")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "得")
docs <- tm_map(docs, toSpace, "可能")
docs <- tm_map(docs, toSpace, "來")
docs <- tm_map(docs, toSpace, "一")
docs <- tm_map(docs, toSpace, "去")
docs <- tm_map(docs, toSpace, "想")
docs <- tm_map(docs, toSpace, "樣")
docs <- tm_map(docs, toSpace, "過")
docs <- tm_map(docs, toSpace, "他")
docs <- tm_map(docs, toSpace, "知道")
docs <- tm_map(docs, toSpace, "然後")
docs <- tm_map(docs, toSpace, "最後")
docs <- tm_map(docs, toSpace, "所以")
docs <- tm_map(docs, toSpace, "為")
docs <- tm_map(docs, toSpace, "像")
docs <- tm_map(docs, toSpace, "應該")
docs
```
## 詞頻矩陣
```{r}
library(jiebaR)
mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
freqFrame = freqFrame[order(freqFrame$Freq,decreasing=TRUE), ]
library(knitr)
kable(head(freqFrame), format = "markdown")
```
## 文字雲
```{r}
library(wordcloud)
wordcloud(freqFrame$Var1,freqFrame$Freq,
          scale=c(5,0.1),min.freq=50,max.words=150,
          random.order=TRUE, random.color=FALSE, 
          rot.per=.1, colors=brewer.pal(8, "Dark2"),
          ordered.colors=FALSE,use.r.layout=FALSE,
          fixed.asp=TRUE)
```