---
title: "class3real"
author: "廖昱嘉"
date: "2018年7月20日"
output: html_document
---
## 載入所需資料包    
```{r}
library(tm)
library(tmcn)
library(factoextra)
library(Matrix)
```
## TF-IDF
```{r}
docs.corpus <- Corpus(DirSource("./week3"))
docs.seg <- tm_map(docs.corpus, segmentCN)
docs.tdm <- TermDocumentMatrix(docs.seg)
#以上三行是詞頻矩陣
docs.tf <- apply(as.matrix(docs.tdm), 2, function(word) { word/sum(word) })
idf <- function(doc) {
  return ( log2( length(doc)+1 / nnzero(doc)) )
}
docs.idf <- apply(as.matrix(docs.tdm), 1, idf)
docs.tfidf <- docs.tf * docs.idf
#以上是tfidf
```
## PCA和繪圖    
```{r}
docs.pca <- prcomp(docs.tfidf, scale = T)
#R語言已經有PCA的函數了，套上去就對了!
fviz_eig(docs.pca)
# Show the percentage of variances explained by each principal component.
# 由這張圖可以知道，一維空間時的可解釋變異最高，而到二維以後就急速下降並且差別不大
fviz_pca_ind(docs.pca, geom.ind = c("point"), col.ind = "cos2")
# Graph of individuals. Individuals with a similar profile are grouped together.
# 這張圖是個體在dim1和2的圖，大部分的個體(individual)都集中在一起不論是哪一組(group)都一樣集中在同一區
fviz_pca_var(docs.pca, col.var = "contrib",repel = TRUE)
# Positive correlated variables point to the same side of the plot. Negative correlated variables point to opposite sides of the graph.
# 大部分的變數在dim1都是屬於負相關，而在dim2大多屬於正相關，除了少數幾個時段不論dim1,2都是負相關
fviz_pca_biplot(docs.pca, geom.ind = "point",repel = TRUE)
# 這圖是前兩張圖的結合，把individual和variable都畫在同一張圖上，由此可知大部分的點與資料都集中在dim1,2的負相關區
docs.eig <- get_eig(docs.pca)
docs.var <- get_pca_var(docs.pca)
docs.ind <- get_pca_ind(docs.pca)
```
## K-means    
```{r}
ind.coord2 <- docs.ind$coord[, 1:2]
wss <- c()
for (i in 1:10) { wss[i] <- kmeans(ind.coord2, i)$tot.withinss }
plot(wss, type = "b")

km <- kmeans(ind.coord2, 3)
plot(ind.coord2, col = km$cluster)
points(km$centers, col = 1:3, pch = 8, cex = 2)
# 分成三個區塊，但其都在dim1的負值區域，而在dim2大部分都是正值區。
```


